name: object_counter_app
description: "Professional AI Object Counter App in Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # مدیریت دوربین و گالری
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  
  # اجرای مدل TFLite سازگار با دارت 3.3
  tflite_flutter: ^0.10.4
  
  # پردازش تصویر
  image: ^4.1.7
  
  # مدیریت دسترسی‌ها سازگار با دارت 3.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/
